name: My file explorer
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_HERE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HERE }}
          aws-region: us-west-1

      - name: Deploy Static site
        run: aws s3 sync . s3://shipmnthost  --delete
